apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-backend
  template:
    metadata:
      labels:
        app: event-backend
    spec:
      containers:
        - name: event-backend
          image: springbootimage  # (or your DockerHub image if pushed)
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mySql
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Vishal@06
---
apiVersion: v1
kind: Service
metadata:
  name: event-backend
spec:
  selector:
    app: event-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
